"""Add employee details to user model

Revision ID: d366af0eba59
Revises: 
Create Date: 2025-09-28 18:30:37.389767

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd366af0eba59'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('employee_id', sa.String(), nullable=False))
    op.add_column('users', sa.Column('department', sa.String(), nullable=False))
    op.add_column('users', sa.Column('date_of_birth', sa.Date(), nullable=False))
    op.drop_index(op.f('ix_users_name'), table_name='users')
    op.create_index(op.f('ix_users_employee_id'), 'users', ['employee_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_employee_id'), table_name='users')
    op.create_index(op.f('ix_users_name'), 'users', ['name'], unique=False)
    op.drop_column('users', 'date_of_birth')
    op.drop_column('users', 'department')
    op.drop_column('users', 'employee_id')
    # ### end Alembic commands ###
